"""Deterministic writer: fixtures_emission JSON → fixtures/ subpackage.

Input must conform to .claude/schemas/fixtures_emission.schema.json.
Output is a set of files written into <package_name>/fixtures/:

    fixtures/__init__.py        — exports ALL_FIXTURES: list[Callable]
    fixtures/<id>.py            — one per fixture, defines make_<id>() factory

Each factory is a zero-arg callable that returns
`(inputs: dict, fixture_id: str, description: str)` — the contract enforced
by mellea_skills_compiler.toolkit.file_utils.load_fixtures.

The model never writes Python source for fixtures directly. This makes drift
shapes (pytest-style tests, INPUT-only modules, etc.) structurally unreachable.
"""

import json
import re
from pathlib import Path
from typing import Any


_HEADER_FIXTURE = (
    '"""Auto-generated by melleafy from fixtures_emission JSON. Fixture id="{fid}"."""'
)


def _value_repr(value: Any) -> str:
    """Produce safe Python source for a fixture input value.

    Multi-line strings are triple-quoted for readability; nested dicts and
    lists recurse. Everything else falls through to repr().
    """
    if isinstance(value, str):
        if "\n" in value and '"""' not in value:
            return f'"""{value}"""'
        return repr(value)
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = [f"{_value_repr(k)}: {_value_repr(v)}" for k, v in value.items()]
        return "{" + ", ".join(items) + "}"
    if isinstance(value, list):
        if not value:
            return "[]"
        items = [_value_repr(v) for v in value]
        return "[" + ", ".join(items) + "]"
    return repr(value)


def _render_inputs_block(inputs: dict[str, Any]) -> str:
    """Render the inputs dict as a Python literal, one key per line for readability."""
    if not inputs:
        return "    inputs: dict = {}"
    lines = ["    inputs = {"]
    for key, value in inputs.items():
        lines.append(f"        {_value_repr(key)}: {_value_repr(value)},")
    lines.append("    }")
    return "\n".join(lines)


def render_fixture(fixture: dict[str, Any]) -> str:
    """Render a single fixture spec as the contents of fixtures/<id>.py."""
    fid = fixture["id"]
    description = fixture["description"]
    inputs = fixture.get("inputs", {})

    body_lines = [
        _HEADER_FIXTURE.format(fid=fid),
        "",
        "",
        f"def make_{fid}():",
        _render_inputs_block(inputs),
        f"    return inputs, {_value_repr(fid)}, {_value_repr(description)}",
        "",
    ]
    return "\n".join(body_lines)


def render_init(fixtures: list[dict[str, Any]], coverage_doc: str | None = None) -> str:
    """Render fixtures/__init__.py exporting ALL_FIXTURES."""
    lines: list[str] = []
    if coverage_doc:
        lines.append('"""')
        lines.append(coverage_doc.strip())
        lines.append('"""')
    else:
        lines.append('"""Auto-generated by melleafy from fixtures_emission JSON."""')

    lines.append("from typing import Callable")
    lines.append("")

    for fixture in fixtures:
        fid = fixture["id"]
        lines.append(f"from .{fid} import make_{fid}")

    lines.append("")
    lines.append("ALL_FIXTURES: list[Callable] = [")
    for fixture in fixtures:
        fid = fixture["id"]
        lines.append(f"    make_{fid},")
    lines.append("]")
    lines.append("")

    return "\n".join(lines)


def _validate_ids(fixtures: list[dict[str, Any]]) -> None:
    """Catch contract violations the JSON schema cannot express in pure structure."""
    seen: set[str] = set()
    pattern = re.compile(r"^[a-z][a-z0-9_]*$")
    for fixture in fixtures:
        fid = fixture["id"]
        if not pattern.match(fid):
            raise ValueError(f"fixture id {fid!r} is not a valid snake_case identifier")
        if fid in seen:
            raise ValueError(f"duplicate fixture id {fid!r}")
        seen.add(fid)


def write(emission: dict[str, Any] | str, fixtures_dir: str | Path) -> list[Path]:
    """Write the rendered fixtures/ subpackage to fixtures_dir.

    Args:
        emission: dict conforming to fixtures_emission.schema.json, or a JSON string.
        fixtures_dir: target directory (typically <package_name>/fixtures/). Created if absent.

    Returns:
        List of paths written, in deterministic order: __init__.py first, then per-fixture files.
    """
    if isinstance(emission, str):
        emission = json.loads(emission)

    fixtures = emission["fixtures"]
    coverage_doc = emission.get("coverage_doc")

    _validate_ids(fixtures)

    fixtures_path = Path(fixtures_dir)
    fixtures_path.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []

    init_path = fixtures_path / "__init__.py"
    init_path.write_text(render_init(fixtures, coverage_doc), encoding="utf-8")
    written.append(init_path)

    for fixture in fixtures:
        fid = fixture["id"]
        fixture_path = fixtures_path / f"{fid}.py"
        fixture_path.write_text(render_fixture(fixture), encoding="utf-8")
        written.append(fixture_path)

    return written
